feat DishPop
ssxxxxgrace/OrderHere-frontend pull request #2
Opened 2023-11-02 05:29 UTC by cansibi

- Added `DishDetails` to get dish name, ingredients and price.
- Added `QuantityControls` to plus or minus Quantity by using button
- Added `index` to perfom a dialog include above modules

2023-11-02 05:37 UTC, cansibi commented
I'm coding the api to get dish details and wait for the shop cart to imply the add button function

2023-11-26 12:59 UTC, Qiming-Liu requested changes

2023-11-26 12:59 UTC, Qiming-Liu commented on components/DishPopUp/DishPopUp.js
> +// 弹窗组件
No Chinese comment

2023-11-27 10:08 UTC, Qiming-Liu approved these changes

2023-11-27 10:08 UTC, merged